<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Portal das Receitas</title>

         <?php
        echo $this->headLink();
        echo $this->headScript();
        echo $this->JQuery();
        ?>

    </head>
<body>
	<!-- HEADER -->
	<header class="container-fluid">
		<div class="row-fluid">
			<div class="span12">
				<div class="navbar">
					<div class="navbar-inner">
						<div class="container">
							<h2>Portal das Receitas</h2>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<!-- / HEADER -->

	<!-- CLASSE QUE DEFINE O CONTAINER COMO FLUIDO (100%) -->
	<div class="container-fluid">
		<!-- CLASSE PARA DEFINIR UMA LINHA -->
		<div class="row-fluid">
			<!-- COLUNA OCUPANDO 2 ESPAÇOS NO GRID -->
			<div class="span2">
				<h2>Menu</h2>
				<ul class="nav nav-tabs nav-stacked">
					<li><a href="/ingrediente/listar"> <i class="icon-star"></i>
							Ingredientes
					</a></li>
					<li><a href="/receita/listar"> <i class="icon-star"></i> Receitas
					</a></li>
					<li><a href="/Usuario/listar"> <i class="icon-star"></i> Usuarios
					</a></li>
					<li><a href="/usuario/sair"> <i class="icon-star"></i> Logoff
					</a></li>
				</ul>
			</div>
			<!-- COLUNA OCUPANDO 10 ESPAÇOS NO GRID -->
			<div class="span10">
				<div class="well">
                        <?php echo $this->layout()->content; ?>
                    </div>
			</div>
		</div>
	</div>
</body>
</html>


