<table class="table table-striped">  
    <caption><h4>Listagem de Ingredientes</h4></caption>
    <thead>  
        <tr>  
            <th>Id</th>  
            <th>Nome</th>  
            <th>Unidade de Medida</th>  
            <th colspan="3">Ações</th>
        </tr>  
    </thead>  
    <tbody>  
        <?php foreach ($this->registros as $obj) { ?> 
            <tr>  
                <td><?php echo $obj->__get('id'); ?></td>  
                <td><?php echo $obj->__get('nome'); ?> </td>  
                <td><?php echo $obj->__get('unidadeMedida'); ?></td>  
                <td><a href="/ingrediente/editar/id/<?php echo $obj->__get('id');?>"><i class="icon-edit"></i></a></td>  
                <td><a href="/ingrediente/excluir/id/<?php echo $obj->__get('id'); ?>"><i class="icon-trash"></i></a></td>  
                <td><a href="/ingrediente/visualizar/id/<?php echo $obj->__get('id'); ?>"><i class="icon-zoom-in"></i></a></td>  
            </tr>  
        <?php } ?>
        <tr>
           <td><input type="button" class="btn-success" value="Novo" onclick="window.location='inserir'"/></td> 
           <td colspan="5">
             <?php //echo $this->paginationControl($this->lista, 'Sliding', 'paginacao.phtml'); ?>
            </td>
        </tr>
    </tbody>  
</table>